config/routes.rb
Markcase::Application.routes.draw do


  match '/' => 'application#index', :as => 'root'
  match '/home' => 'users#home', :as => 'home'
  match '/home/tag/:tag' => 'users#home', :as => 'home_tag'
  match '/reset_password' => 'settings#reset_password', :as => 'reset_password'

  resources :sessions
  resources :users
  resources :settings 
  resources :password_resets
  resources :tags
  resources :movies
  resources :bookmarks do 
    collection  do 
      delete 'multiple'
      get 'description'
    end
  end
  resources :categories
  
  #admin namespace route
  match 'admin/login' => 'admin::sessions#new', :as => 'admin_login'
  match 'admin/logout' => 'admin::sessions#destroy', :as => 'admin_logout'
  namespace :admin do 
    resources :users do 
      resources :categories
      collection do 
        get 'get_bookmarks/:user_id' => 'users#get_bookmarks', :as => 'get'
        get 'get_categories/:user_id' => 'users#get_categories', :as => 'get'
      end
    end
    #resources :categories 
    resources :bookmarks do 
      collection do 
        get 'tags/:tag' => 'bookmarks#tags', :as => 'tags'
        get 'tag'
      end
    end
    resources :sessions, :only => ['create']
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :description, :email, :password, :username, :password_confirmation
  validates_presence_of :username, :email ,:password, :on => :create
  validates_confirmation_of :password, message: '两次密码不相同'

  has_many :bookmarks  
  has_many :categories
  acts_as_tagger

  self.per_page = ENV['PER_PAGE']
    
    
  def password
    @password
  end

  def password=(password)
    return unless password
    @password = password
    generate_password(password)
  end
  
  def reset_password(args)
    
    if Digest::SHA256.hexdigest(self.salt + args[:password]) == self.hashed_password
      self.password = args[:new_password]
      return save
    end
  end

  def self.authenticate(email,pwd)
    user = User.find_by_email(email)
    if user && Digest::SHA256.hexdigest(user.salt + pwd)==
        user.hashed_password
      return user
    end
    false
  end
  
  def self.register(args)
    return if User.find_by_username(args[:username]) 
    user = User.create(User.analysis(args))
    user.save!
    user
  end
    
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_send_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
 
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
private

  def generate_password(pass)
    salt = Array.new(10) { rand(512).to_s(36) }.join
    self.salt, self.hashed_password =
      salt, Digest::SHA256.hexdigest(salt+pass)
  end
  
  def self.analysis(args)
    {username: args[:username], password: args[:password], password_confirmation: args[:password_confirmation],
    email: args[:email]}
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  expose(:users) { User.paginate(page: params[:page])}
  expose(:user)
  expose(:categories) { user.categories }
  expose(:bookmarks) { user.bookmarks}
  expose(:bookmark) { user.bookmarks.build }
     
  def index
    #@users = User.paginate(page: params[:page]) 
    @users = users
    respond_to do |format|
      format.html  
      format.js { render layout: false }
    end
  end
  def create
    if user.save 
      redirect_to admin_users_url, notice: "Successfully Created user"
    else
      flash[:error] = "error Created user"
      redirect_to admin_users_url
    end 
  end

  def update
    if user.update_attributes(params[:user])  
      redirect_to admin_user_url(user), notice: "Successfully Updated user"
    else
      flash[:error] = "error updated user"
      redirect_to edit_admin_user_url
    end
  end

  def destroy
    user.destroy
    respond_to do |format|
      format.html {    
        redirect_to admin_users_url, notice: "Successfully Destroyed user" }
      format.json { render json: { :message => "user has been deleted"} }
    end
  end

  def get_bookmarks
    respond_to do |format|
      format.json { render json: bookmarks }
    end
  end

  def get_categories
    respond_to do |format|
      format.json { render json: categories}
    end
  end

end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController

  expose(:users)
  expose(:user) { User.find(current_user.id)}
  expose(:categories) { user.categories}
  expose(:bookmarks) { user.bookmarks.order("id desc").paginate(page: params[:page])}

  def index
  end

  def create
    @user = User.register(params)
    if @user  
      session[:user] = @user
      redirect_to home_path, notice: "注册成功！"
    else
      flash[:error] = "your email or password are incorrect relase try again"       
      redirect_to root_path    
    end

  end

  def update
    
    if user.update_attributes(params[:user]) 
      redirect_to settings_url, notice: "successfully updated your information"      
    else
      flash[:error] = "error udpated your information"      
      redirect_to settings_url
    end
  end

  def home
    @categories = categories
    @bookmarks = bookmarks.where(inbox: false)
    Rails.logger.info do
      puts @bookmarks
    end
    respond_to   do |format|
      format.html
      format.js { render layout: false } 
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookmarks.html.erb
        <% @bookmarks.each do |bookmark|%>
        <li class="media  bookmark-item" id="bookmark-item-<%= bookmark.id %>" >
          <%= hidden_field_tag bookmark.id %>
          <div class="media-body">
            <div class="span1 pull-left">
              <%= check_box_tag "id[]", bookmark.id %>
            </div>
            <div class="span11 ">
              <%# link_to "http://#{bookmark.link}" do %>
              <%= link_to bookmark.link do %>
                <h4><%= bookmark.title %></h4>
              <% end %>
              <small><%= bookmark.link %></small>
              <%= link_to bookmark_path(bookmark), title: '喜欢', class: 'bookmark-star', remote: true, format: 'js', method: :put do %>
              <%# link_to '#', title: '喜欢', class: 'bookmark-star' do %>
                <i class="icon-star <%= 'icon-white' unless bookmark.star%>"></i>
              <% end %>
              <a href="#" title="添加标签"   class="tag-button"><i class="icon-tags"></i></a>
              <%= link_to '推荐', new_movie_path(url: bookmark.link, title: bookmark.title), class: 'btn', remote: true %>
              <ul class="has_tags pull-right" data-id="<%= bookmark.id%>">
                <li>标签:</li>
                <% bookmark.tags.each do |tag|%>
                  <li><%= link_to tag,  tag_path(tag),  class: "tag-link tag-background" %></li>
                <% end %>
              </ul>                             
              <ul id="myTags" class="add-tags pull-right" name="<%= bookmark.id%>">
                <% bookmark.tags.each do |tag|%>
                  <li><%= tag %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </li> 
        <% end %>
        <div class="flickr_pagination">  
          <% if @bookmarks.present? %>
            <%= will_paginate @bookmarks, renderer: BootstrapPagination::Rails %>  
          <% end %>
        </div>

app/views/users/_categories.html.erb
<% @categories.each do |category|%>
  <li >
    <%= link_to category_path(category), remote: true,  class: " categories-list" do %>
      <i class="icon-folder-open"></i> <%= category.title%><!--<i class="pull-right icon-remove"></i>-->
      <%= link_to category_path(category), class: "category-remove pull-left", remote: true, method: :delete do %>
        <i class="icon-remove"></i>
      <% end %>
    <% end %> 
  </li>
<% end %>

app/views/users/_new_movie_modal.html.erb
<%= form_tag movies_path, class: 'modal fade', id: 'add-movie' do %>
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>添加电影到推荐列表</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <%= submit_tag '推荐', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/users/home.html.erb
<!--<link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet"> 

-->

<div class="row-fluid">
  <div class="span3">
 	  <!-- Left  -->
  	<div class="left">            	
      <ul class="nav   nav-tabs nav-stacked">
        <li class="head">
          <div>
            <!--<img data-src="holder.js/300x200"  src="<%= image_path("head.png")%>" class="img-polaroid">-->
            <%= image_tag avatar_url(current_user,150), class: "img-rounded img-ploaroid"%>
          </div>
        </li>
        <li>
          <%= link_to  home_path do  %>
            <i class="icon-home"></i> &nbsp;主页
          <% end %>
        </li>
        <li>
          <%= link_to bookmark_path(params[:show_type]='inbox'), remote: true, "data-type" => "json", class: "inbox" do %>
            <i class="icon-inbox"></i>  &nbsp;归档
          <% end %>
        </li>                    
        <li>
          <%= link_to bookmark_path(params[:show_type]='favorite'), remote: true, "data-type" => "json", class: "favorite" do %>
            <i class="icon-star"></i>  &nbsp;喜欢
          <% end %>
        </li>  
        <li class="divider"></li>
        <li class="nav-header">收藏夹</li>
          <%= render 'categories' %> 
        <li>
          <%= link_to new_category_path , remote: true do %>
            <i class="icon-plus"></i>  &nbsp;创建收藏夹
          <% end %>
        </li>
        <li class="divider"></li>
        <li class="nav-header">标签</li>                              
        <% user.owned_tags.limit(5).order('id desc').each do |tag| %>
          <li>
            <%= link_to  tag_path(tag.name), class: "tag-link" do %>
              <i class="icon-tag"></i> <%= tag.name %>
            <% end %>
          </li>
        <% end %>
        <li><%= link_to "更多标签", tags_path, class: "more-tags", remote: true, format: "json" %><li>
      </ul>
    </div>
    <!-- left END -->
  </div>
  <div class="span6">
    <!-- center  -->  
    <div class="center">
      <%= form_tag  multiple_bookmarks_path, method: :delete do %>
      <div class=" control_bar">
        <div class="span2">
          <%= check_box_tag "select-all",params[:ids]%> 全选
        </div>
        <div class="span5  input-append "> 
            <% categories_array = categories.map { |c| [c.title,c.id]}%>
            <%= select_tag "category_id", options_from_collection_for_select(categories,'id','title'), class: 'span5'%>
            <%= button_tag "移动至收藏夹", class: "btn", name: "move_button" %>
        </div>
        <div class="span5 btn-group">
          <%= button_tag  class: 'btn btn-danger', name: "destroy_button" do %>
            <i class="icon-trash icon-white"></i> 删除选中
          <% end %>
          <%= button_tag class: 'btn btn-inverse', name: "inbox_button" do  %>
            <i class="icon-inbox icon-white"></i> 归档 
          <% end %>
        </div>
      </div>
      <ul class="bookmark-list media-list">
        <%= render 'bookmarks'%>
      </ul>
      <% end %>
    </div>
    <!-- center END -->
  </div>
  <div class="span3 ">
    <!-- right -->
    <div class="right">
      <img class='description-image' src="" />
      <h4 class="title-of-description">电影剧情简介</h4>
      <p class="description">
               点击左面的书签 这里将会显示它的简介信息(如果它有的话！)
      </p>
      <form>
        <textarea class="bookmark_note" placeholder="还没有笔记呢..." ></textarea>
      </form>
    </div>
    <!-- right END -->
  </div>        
</div>


<!-- Alert -->



<!-- Alert END-->

<!-- share movies modal -->
<%# render partial: 'new_movie_modal' %>



app/views/users/home.js.erb
$(".bookmark-list").html("<%= escape_javascript(render "bookmarks")%>")