config/routes.rb
Markcase::Application.routes.draw do


  match '/' => 'application#index', :as => 'root'
  match '/home' => 'users#home', :as => 'home'
  match '/home/tag/:tag' => 'users#home', :as => 'home_tag'
  match '/reset_password' => 'settings#reset_password', :as => 'reset_password'

  resources :sessions
  resources :users
  resources :settings 
  resources :password_resets
  resources :tags
  resources :movies
  resources :bookmarks do 
    collection  do 
      delete 'multiple'
      get 'description'
    end
  end
  resources :categories
  
  #admin namespace route
  match 'admin/login' => 'admin::sessions#new', :as => 'admin_login'
  match 'admin/logout' => 'admin::sessions#destroy', :as => 'admin_logout'
  namespace :admin do 
    resources :users do 
      resources :categories
      collection do 
        get 'get_bookmarks/:user_id' => 'users#get_bookmarks', :as => 'get'
        get 'get_categories/:user_id' => 'users#get_categories', :as => 'get'
      end
    end
    #resources :categories 
    resources :bookmarks do 
      collection do 
        get 'tags/:tag' => 'bookmarks#tags', :as => 'tags'
        get 'tag'
      end
    end
    resources :sessions, :only => ['create']
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :description, :email, :password, :username, :password_confirmation
  validates_presence_of :username, :email ,:password, :on => :create
  validates_confirmation_of :password, message: '两次密码不相同'

  has_many :bookmarks  
  has_many :categories
  acts_as_tagger

  self.per_page = ENV['PER_PAGE']
    
    
  def password
    @password
  end

  def password=(password)
    return unless password
    @password = password
    generate_password(password)
  end
  
  def reset_password(args)
    
    if Digest::SHA256.hexdigest(self.salt + args[:password]) == self.hashed_password
      self.password = args[:new_password]
      return save
    end
  end

  def self.authenticate(email,pwd)
    user = User.find_by_email(email)
    if user && Digest::SHA256.hexdigest(user.salt + pwd)==
        user.hashed_password
      return user
    end
    false
  end
  
  def self.register(args)
    return if User.find_by_username(args[:username]) 
    user = User.create(User.analysis(args))
    user.save!
    user
  end
    
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_send_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
 
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
private

  def generate_password(pass)
    salt = Array.new(10) { rand(512).to_s(36) }.join
    self.salt, self.hashed_password =
      salt, Digest::SHA256.hexdigest(salt+pass)
  end
  
  def self.analysis(args)
    {username: args[:username], password: args[:password], password_confirmation: args[:password_confirmation],
    email: args[:email]}
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  expose(:users) { User.paginate(page: params[:page])}
  expose(:user)
  expose(:categories) { user.categories }
  expose(:bookmarks) { user.bookmarks}
  expose(:bookmark) { user.bookmarks.build }
     
  def index
    #@users = User.paginate(page: params[:page]) 
    @users = users
    respond_to do |format|
      format.html  
      format.js { render layout: false }
    end
  end
  def create
    if user.save 
      redirect_to admin_users_url, notice: "Successfully Created user"
    else
      flash[:error] = "error Created user"
      redirect_to admin_users_url
    end 
  end

  def update
    if user.update_attributes(params[:user])  
      redirect_to admin_user_url(user), notice: "Successfully Updated user"
    else
      flash[:error] = "error updated user"
      redirect_to edit_admin_user_url
    end
  end

  def destroy
    user.destroy
    respond_to do |format|
      format.html {    
        redirect_to admin_users_url, notice: "Successfully Destroyed user" }
      format.json { render json: { :message => "user has been deleted"} }
    end
  end

  def get_bookmarks
    respond_to do |format|
      format.json { render json: bookmarks }
    end
  end

  def get_categories
    respond_to do |format|
      format.json { render json: categories}
    end
  end

end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController

  expose(:users)
  expose(:user) { User.find(current_user.id)}
  expose(:categories) { user.categories}
  expose(:bookmarks) { user.bookmarks.order("id desc").paginate(page: params[:page])}

  def index
  end

  def create
    @user = User.register(params)
    if @user  
      session[:user] = @user
      redirect_to home_path, notice: "注册成功！"
    else
      flash[:error] = "your email or password are incorrect relase try again"       
      redirect_to root_path    
    end

  end

  def update
    
    if user.update_attributes(params[:user]) 
      redirect_to settings_url, notice: "successfully updated your information"      
    else
      flash[:error] = "error udpated your information"      
      redirect_to settings_url
    end
  end

  def home
    @categories = categories
    @bookmarks = bookmarks.where(inbox: false)
    Rails.logger.info do
      puts @bookmarks
    end
    respond_to   do |format|
      format.html
      format.js { render layout: false } 
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
                <%= form_for [:admin,user] do |f|%>
						    <fieldset>
                  <%= f.label "用户名"%>
                  <%= f.text_field :username %>
						    </fieldset>
						    <fieldset>
                  <%= f.label "邮箱"%>
                  <%= f.email_field :email %>
						    </fieldset>
                <% if action_name == "new"%>
						      <fieldset>
                    <%= f.label "密码"%>
                    <%= f.password_field :password %>
						      </fieldset>
						      <fieldset>
                    <%= f.label "确认密码"%>
                    <%= f.password_field :password_confirmation %>
						      </fieldset>
                <% end %>
						    <fieldset>
                  <%= f.label "个性签名" %>
                  <%= f.text_area :description, rows: 12 %>
						    </fieldset>
						    <fieldset style="width:48%; float:left; margin-right: 3%;"> <!-- to make two field float next to one another, adjust values accordingly -->
							    <label>Category</label>
							    <select style="width:92%;">
								    <option>Articles</option>
								    <option>Tutorials</option>
								    <option>Freebies</option>
							    </select>
						    </fieldset>
						    <fieldset style="width:48%; float:left;"> <!-- to make two field float next to one another, adjust values accordingly -->
							    <label>Tags</label>
							    <input type="text" style="width:92%;">
						    </fieldset><div class="clear"></div>
				    </div>
			    <footer>
				    <div class="submit_link">
					    <select>
						    <option>Draft</option>
						    <option>Published</option>
					    </select>
              <%= f.submit "提交", class: "alt_btn"%>
              <%= f.submit "Reset"%>
				    </div>
			    </footer>
          <% end %>

app/views/admin/users/_users.html.erb
      <table class="tablesorter display" cellspacing="0" id="users">
        <thead>
          <tr>
            <th></th>
            <th>用户名</th>
            <th>邮箱地址</th>
            <th>最后登录时间</th>
            <th>操作</th>
          </tr>
        </thead>
       <tbody>
        <% @users.each do |user|%> 
          <tr>
            <td><%= check_box_tag "users-item", user.id %></td>
            <td><%= link_to user.username, admin_user_path(user)%></td>
            <td><%= user.email %></td>
            <td><%= user.updated_at %></td>
            <td>
            <%= link_to image_tag("admin/icn_edit.png"), edit_admin_user_path(user), title: '编辑' %>
            <%= link_to image_tag("admin/icn_trash.png"), admin_user_path(user), method: :delete, title: "删除",
              confirm: "Are you sure", remote: true, 'data-type' => 'json' %>
            </td>
          </tr>
        <% end %>
        
        </tbody>
      </table>
      <div class="flickr_pagination">  
        <%= will_paginate @users %>  
      </div>       

app/views/admin/users/edit.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">用户管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
		    <article class="module width_full">
          <header><h3>修改用户信息</h3></header>
				    <div class="module_content">
            <%= render 'form' %>
       	 </article><!-- end of edit user information -->        
      </div>
    </div>
</article><!-- end of content manager article -->

app/views/admin/users/index.html.erb
<article class="module width_3_quarter">
  <header>
    <h3 class="tabs_involved">用户管理</h3>
		<ul class="tabs">
   			<li><a href="#tab1">用户</a></li>
    		<li><a href="#tab2">书签</a></li>
    		<li><a href="#tab3">收藏夹</a></li>    		
		</ul>    
  </header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
      <div id="users-list">
        <%= render 'users' %>
      </div>
      
      </div>
      <div id="tab2" class="tab_content">
      <table class="tablesorter display" cellspacing="0" id="bookmarks-list">
        <thead>
        <tr>
          <th>书签链接</th>
          <th></th>
          <th>操作</th>
        </tr>
       </thead>
       <tbody>
        <% bookmarks.each do |book|%> 
          <tr>
            <td><%= check_box_tag "users-item", book.id %></td>
            <td><%= link_to book.link, admin_bookmark_path(book)%></td>
            <td><%= book.user.username %></td>
            <td><%= book.updated_at %></td>
            <td>
            <%= link_to image_tag("admin/icn_edit.png"), edit_admin_bookmark_path(book), title: "编辑"%>
              
            <%= link_to image_tag("admin/icn_trash.png"), admin_boomark_path(book), method: :delete, title: "删除" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
     <div id="tab3" class="tab_content">
        <table class="tablesorter display" cellspacing="0" id="categories-list">
          <thead>
            <tr>
              <th>收藏夹名</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
</article><!-- end of content manager article -->

app/views/admin/users/index.js.erb
$("#users-list").html("<%= escape_javascript(render 'users') %>");
$(".pagination a").on("click",function(){
  $.getScript(this.href);
  return false;
});

app/views/admin/users/new.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">用户管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
		    <article class="module width_full">
          <header><h3>修改用户信息</h3></header>
				    <div class="module_content">
            <%= render 'form' %>
        </article><!-- end of edit user information -->        
      </div>
    </div>
</article><!-- end of content manager article -->

app/views/admin/users/show.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">用户管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
        <table class="table">
          <tr> 
            <td>头像：</td>
            <td><%= image_tag avatar_url(user,150)%></td>
          </tr>
          <tr> 
            <td>用户名：</td>
            <td><%= user.username %></td>
          </tr>
          <tr> 
            <td>E-mail：</td>
            <td><%= user.email %></td>
          </tr>
          <tr> 
            <td>个性签名：</td>
            <td><%= user.description%></td>
          </tr>
        </table>
      </div>
    </div>
</article><!-- end of content manager user -->
<!--<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">书签</h3></header>
    <div class="tab_container">
      <div id="tab2" class="stab_content">
 -->
		    <article class="module width_3_quarter">
		     
          <header><h3>添加书签</h3></header>
				    <div class="module_content">
                <%= form_for [:admin,bookmark] do |f| %>
						    <fieldset>
                  <%= f.label "链接" %>
                  <%= f.text_field :link %>
						    </fieldset>
						    <fieldset style="width:48%; float:left; margin-right: 3%;">
							    <%= f.label "收藏夹"%> 
							    <% categories_array = categories.map { |c| [c.title,c.id] } %>
							    <%= f.select :category_id,options_for_select(categories_array)%>
						    </fieldset>
						    <fieldset style="width:48%; float:left;"> 
							    <%= f.label "标签"%>
							    <%= f.hidden_field :tag_list %>
							    <ul id="bookmarkTags" class="pull-left" style="width:80%; float:left; margin-right: 3%;">
                    <% bookmark.tag_list.each do |tag| %>
                      <li><%= tag %></li>
                    <% end %>
                  </ul>
						    </fieldset><div class="clear"></div>
				    </div>
			    <footer>
				    <div class="submit_link">
              <%= f.submit "提交", class: "alt_btn"%>
              <%= f.submit 'Reset'%>
				    </div>
			    </footer>
          <% end %>          
        </article><!-- end of edit user information -->       
        <!-- 
      </div>
    </div>
</article>-->

<!-- categories add -->
		    <article class="module width_3_quarter">
		     
          <header><h3>添加收藏夹</h3></header>
                <%= form_for [:admin,user,categories.build] do |f| %>
				    <div class="module_content">
						    <fieldset>
                  <%= f.label "名称" %>
                  <%= f.text_field :title %>
						    </fieldset><div class="clear"></div>
				    </div>
			    <footer>
				    <div class="submit_link">
              <%= f.submit "提交", class: "alt_btn"%>
              <%= f.submit "Reset"%>
				    </div>
			    </footer>
          <% end %>          
        </article><!-- end of edit user information -->      