config/routes.rb
Markcase::Application.routes.draw do


  match '/' => 'application#index', :as => 'root'
  match '/home' => 'users#home', :as => 'home'
  match '/home/tag/:tag' => 'users#home', :as => 'home_tag'
  match '/reset_password' => 'settings#reset_password', :as => 'reset_password'

  resources :sessions
  resources :users
  resources :settings 
  resources :password_resets
  resources :tags
  resources :movies
  resources :bookmarks do 
    collection  do 
      delete 'multiple'
      get 'description'
    end
  end
  resources :categories
  
  #admin namespace route
  match 'admin/login' => 'admin::sessions#new', :as => 'admin_login'
  match 'admin/logout' => 'admin::sessions#destroy', :as => 'admin_logout'
  namespace :admin do 
    resources :users do 
      resources :categories
      collection do 
        get 'get_bookmarks/:user_id' => 'users#get_bookmarks', :as => 'get'
        get 'get_categories/:user_id' => 'users#get_categories', :as => 'get'
      end
    end
    #resources :categories 
    resources :bookmarks do 
      collection do 
        get 'tags/:tag' => 'bookmarks#tags', :as => 'tags'
        get 'tag'
      end
    end
    resources :sessions, :only => ['create']
  end
end

app/models/bookmark.rb
#encoding: utf-8
require 'open-uri'

class Bookmark < ActiveRecord::Base

  MAX_ATTEMPTS = ENV['MAX_ATTEMPTS'].to_i
  attr_accessible :category_id, :inbox, :link, :note, :star, :title, :user_id, :tag_list
  belongs_to :user
  belongs_to :category
  self.per_page =  ENV['PER_PAGE']
  acts_as_taggable_on :tags

  
  scope :favorite, lambda { where(star: true)}
  scope :show_inbox, lambda { where(inbox: true)}
  

  # after_create :get_bookmark_title
  after_create :get_movie_link

  def tags
    tags_from(user) 
  end

  def change_star
    update_attribute(:star,!self.star) 
    self.star
  end


  #
  # 通过url获取电影的简介
  #
  def self.get_movie_description(url)

    movie_uri = open(url)

    doc = Nokogiri::HTML.parse(movie_uri)

    text = doc.css('span[property="v:summary"]').text
  end

  #
  # 获取 电影海报
  #
  def self.get_movie_poster(key)

    encode_key = CGI::escape key

    url = "http://www.1905.com/search/index-p-type-film-q-#{encode_key}.html"

    page = Nokogiri::HTML(open(url))

    image_url = page.css("img[title='#{key}']").attr('src').value

    image_url.gsub(/\_[0-9]{3}\_[0-9]{3}\_/,'_200_300_')

  end

  private 


  def get_bookmark_title
    url = "http://#{self.link}"    
    attempts = 0
    begin
      page = Nokogiri::HTML.parse(open(url))
      self.title = page.css('title').text
      self.save
    rescue Exception => e
      attempts = attempts + 1
      retry if attempts < MAX_ATTEMPTS 
    end
    if page.nil?
      self.title = "The URL is incorrect"
      self.save
    end
  end


  #
  # 获取电影的链接
  #
  def get_movie_link

    keywords = CGI::escape self.title

    url = "http://movie.douban.com/subject_search?search_text=#{keywords}"

    uri_handler = open(url)

    page = Nokogiri::HTML.parse(uri_handler)

    if page.blank?

      self.link = ''
      self.save

    else

      movie_url = page.css('.pl2').first.css('a').attr('href').value

      self.link = movie_url

      self.save

    end

  end

  def get_movie_desc

    movie_uri = open(self.link)

    doc = Nokogiri::HTML.parse(movie_uri)

    text = doc.css('span[property="v:summary"]').text

  end


end

app/controllers/admin/bookmarks_controller.rb
class Admin::BookmarksController < AdminController
  
  expose(:bookmarks) { Bookmark.order("id desc").paginate(page: params[:page])}
  expose(:bookmark)
  expose(:bookmarks_with_tag) { Bookmark.tagged_with params[:tag] if params[:tag]}
    
  def index
    respond_to do |format|
      format.html  
      format.js { 
        @bookmarks = User.find(params[:user_id]).bookmarks.order("id desc").paginate(page: params[:page])
        render layout: false 
      }
    end
  end
  def create
    if bookmark.save 
      redirect_to admin_bookmarks_url, notice: "Successfully Created bookmark"
    else
      flash[:error] = "error Created user"
      redirect_to admin_users_url
    end 
  end

  def update
    if bookmark.update_attributes(params[:bookmark])  
      redirect_to admin_bookmark_url(bookmark), notice: "Successfully Updated bookmark"
    else
      flash[:error] = "error updated bookmark"
      redirect_to edit_bookmark_user_url
    end
  end

  def destroy
    bookmark.destroy
    redirect_to admin_bookmarks_url, notice: "Successfully Destroyed bookmark"

  end

  def tag
    if bookmark.user.tag(bookmark,with: params[:tags],on: :tags)
      respond_to do |format|
        format.json { render json: { message: 'success'}}
      end
    else
      respond_to do |format|
        format.json { render json: { message: 'failed'}}
      end
    end
  end
end

app/controllers/bookmarks_controller.rb
#encoding: utf-8
class BookmarksController < ApplicationController
  MAX_ATTEMPTS = 2
  expose(:user) { User.find(current_user.id) }
  expose(:bookmarks) { user.bookmarks} 
  expose(:bookmark)

  def index
    bookmarks.each do |bookmark|
      bookmark[:tag_list] = bookmark.tag_list
    end
    respond_to do |format|
      format.json { render json: bookmarks}
    end
  end

  def new
    
  end

  def create
    if bookmark.save
      respond_to do |format|
        format.html { redirect_to home_url, notice: 'successfully created bookmark'}
        format.json { render json: { message: 'successfully created bookmark'}  }
      end
    else
      respond_to do |format|
        format.html { 
          flash[:error] = 'additions bookmarks failed !'
          redirect_to home_url
        }
        format.json { render json: { message: 'additions bookmarks failed !'} }
      end
    end
  end

  def update
    if bookmark.change_star 
      respond_to do |format|
        format.json { render json: { star: bookmark.star, message: 'successfully updated bookmark'}}
      end
    else
      respond_to do |format|
        format.json { render json: { message: 'failed updated bookmark'} }
      end
    end
  end


  def show
    case params[:id]
      when 'inbox'
        @bookmarks = bookmarks.show_inbox.paginate(page: params[:page])
        respond_to do |format|
          format.json { render json: bookmarks.show_inbox }
          format.js { render layout: false}
        end
      when 'favorite'
        @bookmarks = bookmarks.favorite.paginate(page: params[:page])
        respond_to do |format|
          format.json { render json: bookmarks.favorite }
          format.js { render layout: false}
        end
      when 'note'
        respond_to  do |format|
          format.json { render json: Bookmark.select(:note).find(params[:t_id]).to_json  } 
        end
    end
  end

  def description
    url = params[:url]
    title = params[:title]
    attempts = 0
    begin

      description = Bookmark.get_movie_description url
      image_url = Bookmark.get_movie_poster title

    rescue => e
      attempts += 1
      retry if attempts <= MAX_ATTEMPTS 
    end
    respond_to do |format|
      format.json { render json: {description: description, image_url: image_url} }
    end
  end

  def multiple
    if params[:destroy_button]
      Bookmark.destroy(params[:id])
      flash[:notice] = '已删除选择的书签'
    elsif params[:inbox_button]
      bookmark.each do |bo| 
        unless bo.update_attribute(:inbox,true)
          flash[:error] = '归档失败'
          redirect_to home_url and return
        end
      end
      flash[:notice] = '已归档'
    else
      bookmark.each do |bo|
        unless bo.update_attribute(:category_id, params[:category_id]) 
          flash[:error] = '移动失败'
          redirect_to home_url and return
        end
      end
      flash[:notice] = '移动成功!'
    end
    redirect_to home_url
  end

end

app/helpers/admin/bookmarks_helper.rb
module Admin::BookmarksHelper
end

app/helpers/bookmarks_helper.rb
#encoding: utf-8
module BookmarksHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Context

  def builder_bookmark_list_html(bookmarks)
    bookmarks.each do |bookmark|
      content_tag :li, class: 'media bookmark-item' do
        hidden_field_tag bookmark.id   
        content_tag :div, class: 'media-body' do
          content_tag(:h4, bookmark.title, class: "media-heading" )
          link_to bookmark.link, "http://#{bookmark.link}"
          link_to "#", class: "star", title: "喜欢" do
            content_tag(:i,class: "icon-star icon-white",id: "star-icon")
          end
          link_to "#", title: "添加标签", class: "tag-button" do
            content_tag(:i,class: "icon-tags")
          end
          content_tag :ul, class: "has_tags pull-right", "data-id" => bookmark.id do
            content_tag(:li, '标签')
            bookmark.tag_list.each do |tag|
              content_tag :li  do 
                link_to tag, '/home', class: 'tag-background'
              end
            end
          end
          content_tag :ul, id: 'myTags', class: 'add-tags pull-right'  do
            bookmark.tag_list.each  do |tag|
              content_tag(:li,tag) 
            end
          end
        end
      end
    end
  end
end

app/views/admin/bookmarks/_bookmarks_of_user.html.erb
<table class="tablesorter display" cellspacing="0" >
  <thead>
    <tr>
          <th>书签链接</th>
          <th>标题</th>
          <th>操作</th>
        </tr>
       </thead>
  <tbody>
    <% @bookmarks.each do |book|%> 
      <tr>
        <!--<td><%# check_box_tag "users-item", book.id %></td>-->
        <td><%= link_to book.link, book.link %></td>
        <td><%= link_to book.title, admin_bookmark_path(book) %></td>
        <td>
        <%= link_to image_tag('admin/icn_edit.png'), edit_admin_bookmark_path(book), title: '编辑'%>
          
        <%= link_to image_tag('admin/icn_trash.png'), admin_bookmark_path(book), method: :delete, title: '删除' %>
        </td>
       </tr>
     <% end %>
  </tbody>
</table>
<div class="flickr_pagination">  
  <%= will_paginate @bookmarks %>  
</div>       

app/views/admin/bookmarks/_form.html.erb
                <%= form_for [:admin,bookmark] do |f|%>
						    <fieldset>
                  <%= f.label '电影名'%>
                  <%= f.text_field :title %>
						    </fieldset>
						    <fieldset>
                  <%= f.label "所有者" %>
							    <% users_array = User.order(:username).map { |user| [user.username,user.id]} %>
							    <%= f.select :user_id, options_for_select(users_array), style: "width:92%;" %>                  
						    </fieldset>
						    <fieldset style="width:48%; float:left; margin-right: 3%;"> <!-- to make two field float next to one another, adjust values accordingly -->
							    <%= f.label "收藏夹"%>

							    <% categories_array = Category.order(:id).map { |c| [c.title,c.id] } %>
							    <%= f.select :category_id,options_for_select(categories_array), style: "width:92%;"%>
						    </fieldset>
						    <fieldset style="width:48%; float:left;"> <!-- to make two field float next to one another, adjust values accordingly -->
							    <%= f.label "标签"%>
							    <ul id="bookmarkTags" class="pull-left" data-id="<%= bookmark.id%>" style="width:80%; float:left; margin-right: 3%;">
                    <% bookmark.tags.each do |tag| %>
                      <li><%= tag %></li>
                    <% end %>
                  </ul>
                  
						    </fieldset><div class="clear"></div>
				    </div>
			    <footer>
				    <div class="submit_link">

              <%= f.submit "提交", class: "alt_btn", id: "save-boomark"%>
              <%= f.button "重置", type: :reset %>
				    </div>
			    </footer>
          <% end %>

app/views/admin/bookmarks/edit.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">电影书签管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
		    <article class="module width_full">
          <header><h3>修改书签</h3></header>
				    <div class="module_content">
            <%= render 'form' %>
       	 </article><!-- end of edit user information -->
      </div>
    </div>
</article><!-- end of content manager article -->

app/views/admin/bookmarks/index.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">电影书签管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
      <table class="tablesorter display" cellspacing="0" id="bookmarks">
        <thead>
        <tr>
          <th></th>
          <th>电影书签</th>
          <th>所有者</th>
          <th>操作</th>
        </tr>
       </thead>
       <tbody>
        <% bookmarks.each do |bookmark|%> 
          <tr>
            <td><input type="checkbox"></td>
            <td><%= link_to bookmark.title, admin_bookmark_path(bookmark)%></td>
            <td><%= bookmark.user.username %></td>
            <td>
            <%= link_to image_tag('admin/icn_edit.png'), edit_admin_bookmark_path(bookmark), title: '编辑'%>
              
            <%= link_to image_tag('admin/icn_trash.png'), admin_bookmark_path(bookmark), method: :delete, title: '删除' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
 <div class="flickr_pagination">  
  <%= will_paginate bookmarks %>  
</div>
      </div>
    </div>
</article><!-- end of content manager article -->

app/views/admin/bookmarks/index.js.erb
$("#bookmarks-list").html("<%= escape_javascript(render 'bookmarks_of_user')%>");

app/views/admin/bookmarks/new.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">电影书签管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
		    <article class="module width_full">
          <header><h3>添加书签</h3></header>
				    <div class="module_content">
            <%= render partial: 'form' %>
        </article><!-- end of edit user information -->        
      </div>
    </div>
</article><!-- end of content manager article -->

app/views/admin/bookmarks/show.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">电影书签管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
        <table class="table">
          <tr> 
            <td>电影书签链接：</td>
            <td><%= link_to bookmark.title, bookmark.link %></td>
          </tr>
          <tr> 
            <td>所有者：</td>
            <td><%= link_to bookmark.user.username, admin_user_path(bookmark.user)%></td>
          </tr>
          <tr> 
            <td>标签：</td>
            <td>
              
              <% bookmark.tags.each do |tag|%>
                
                <%= link_to tag, tags_admin_bookmarks_path(tag) %>
              <% end %>
            </td> 
          </tr>          
        </table>
      </div>
    </div>
</article><!-- end of content manager user -->

app/views/admin/bookmarks/tags.html.erb
<article class="module width_3_quarter">
  <header><h3 class="tabs_involved">书签管理</h3></header>
    <div class="tab_container">
      <div id="tab1" class="tab_content">
      <table class="tablesorter display" cellspacing="0" id="bookmarks">
        <thead>
        <tr>
          <th></th>
          <th>书签链接</th>
          <th>所有者</th>
          <th>操作</th>
        </tr>
       </thead>
       <tbody>
        <% bookmarks_with_tag.each do |bookmark|%> 
          <tr>
            <td><input type="checkbox"></td>
            <td><%= link_to bookmark.link,admin_bookmark_path(bookmark)%></td>
            <td><%= bookmark.user.username %></td>
            <td>
            <%= link_to image_tag("admin/icn_edit.png"), edit_admin_bookmark_path(bookmark), title: '编辑'%>
              
            <%= link_to image_tag("admin/icn_trash.png"), admin_bookmark_path(bookmark), method: :delete, title: "删除" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
    </div>
</article><!-- end of content manager article -->