config/routes.rb
Markcase::Application.routes.draw do


  match '/' => 'application#index', :as => 'root'
  match '/home' => 'users#home', :as => 'home'
  match '/home/tag/:tag' => 'users#home', :as => 'home_tag'
  match '/reset_password' => 'settings#reset_password', :as => 'reset_password'

  resources :sessions
  resources :users
  resources :settings 
  resources :password_resets
  resources :tags
  resources :movies
  resources :bookmarks do 
    collection  do 
      delete 'multiple'
      get 'description'
    end
  end
  resources :categories
  
  #admin namespace route
  match 'admin/login' => 'admin::sessions#new', :as => 'admin_login'
  match 'admin/logout' => 'admin::sessions#destroy', :as => 'admin_logout'
  namespace :admin do 
    resources :users do 
      resources :categories
      collection do 
        get 'get_bookmarks/:user_id' => 'users#get_bookmarks', :as => 'get'
        get 'get_categories/:user_id' => 'users#get_categories', :as => 'get'
      end
    end
    #resources :categories 
    resources :bookmarks do 
      collection do 
        get 'tags/:tag' => 'bookmarks#tags', :as => 'tags'
        get 'tag'
      end
    end
    resources :sessions, :only => ['create']
  end
end

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="zh-CN">

<head>
	<meta charset="utf-8"/>
	<title>Markcase 后台管理系统</title>
	
  <%= stylesheet_link_tag "admin" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>

</head>


<body class="<%= controller_name %>">

	<header id="header">
		<hgroup>
			<h1 class="site_title"><a href="index.html">Markcase 后台管理系统</a></h1>
			<h2 class="section_title">Dashboard</h2><div class="btn_view_site"><%= link_to "View Site", root_path%></div>
		</hgroup>
	</header> <!-- end of header bar -->
	
	<section id="secondary_bar">
		<div class="user">
			<p><%= current_admin.username %> </p>
		</div>
		<div class="breadcrumbs_container">
			<article class="breadcrumbs"><a href="index.html">Website Admin</a> <div class="breadcrumb_divider"></div> <a class="current">Dashboard</a></article>
		</div>
	</section><!-- end of secondary bar -->
	
<aside id="sidebar" class="column">
    <form class="quick_search">
      <input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
    </form>
    <hr/>
    <h3>内容管理</h3>
    <ul class="toggle">
      <li class="icn_new_article"><%= link_to "浏览书签", admin_bookmarks_path %></li>
      <li class="icn_new_article"><%= link_to "添加书签", new_admin_bookmark_path %></li>

      <!--<li class="icn_categories"><a href="#">分类</a></li>-->
      <!--<li class="icn_tags"><a href="#">标签</a></li>-->
    </ul>
    <h3>用户管理</h3>
    <ul class="toggle">
      <li class="icn_add_user"><%= link_to "添加一个新用户", new_admin_user_path %></li>
      <li class="icn_view_users"><%= link_to "查看用户", admin_users_path %></li>
      <li class="icn_profile"><%= link_to "编辑用户", admin_users_path %></a></li>
    </ul>
    <h3>Admin</h3>
    <ul class="toggle">
      <!--
      <li class="icn_settings"><a href="#">选项</a></li>
      <li class="icn_security"><a href="#">安全</a></li>
      -->
      <li class="icn_jump_back"><%= link_to "退出", admin_logout_path %></li>
    </ul>
    
    <footer>
      <hr />
      <p><strong>Copyright &copy; 2015 Markcase Admin</strong></p>
      <p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
    </footer>
  </aside><!-- end of sidebar -->
	
	<section id="main" class="column">
    <% if flash[:notice]%>
      <div class="alert alert-success">
        <h4 class="alert_success"><%= flash[:notice] %>
          <button class="close" data-dismiss="alert" type="button">&times;</button>
        </h4>
      </div>
    <% end %>
    <% if flash[:error]%>
      <div class="alert alert-error alert_error">
        <h4><%= flash[:error] %>
          <button class="close" data-dismiss="alert" type="button">&times;</button>
        </h4>
      </div>
    <% end %>
    <%= yield %>
		
	</section>


</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markcase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
<!-- Navbar  -->
<div class="navbar navbar-inverse  navbar-fixed-top">
	<div class="navbar-inner">
    <div class="nav-align">
    	<div class="container" style="width:auto;">
        <!-- Navbar Logo -->
        <a class="brand" href="#">电影推荐网站</a>
        <!-- Navbar link -->
        <ul class="nav">
          <li class="active">
            <%= link_to '首页', root_path %>
          </li>
          <% if controller_name == 'users'%>
            <!--<li><a href="#add-mark" data-toggle="modal">添加电影书签</a></li>-->
            <li>
              <%= link_to '添加电影书签', new_bookmark_path, remote: true %>
            </li>
          <% end %>
        </ul>
        <!-- Navbar link END-->
        <!-- User Info -->
        <ul class="nav pull-right">
          <% unless current_user %>
            <li>
              <a name="relink" data-toggle="modal" href="#register">注册</a>
            </li>
            <li class="dropdown">
              <a  name="link" data-toggle="modal" href="#login">登陆</a>
            </li>
          <% else %>
            <li class="dropdown">
              <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
              <!--<i class="icon-user icon-white"></i>-->
                <%= image_tag avatar_url(current_user, 20)%>
                <%= current_user.username %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to '主页', home_path %></li>
                <li><%= link_to '个人设置', settings_path %></li>
                <li class="divider"></li>
                <li><%= link_to '退出', session_path(current_user), method: :delete %></li>
              </ul>
            </li>            
          <% end %>
        </ul>     
        <!-- User Info END -->       
        </div>    
  </div>
    </div>
</div>
<!-- Navbar END -->

<div class="body">
  <% if flash[:error] %>
  <div class="alert alert-error">
    <button type="button" data-dismiss="alert" class="close">&times;</button>
    <h5><%= flash[:error] %></h5>
  </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" data-dismiss="alert" class="close">&times;</button>
      <h5><%= flash[:notice] %></h5>
    </div>
  <% end %>
  <%= yield %>
</div>

<div id="footer">

  <div class="container">

    <p class="muted credit">&copy;2015 Markcase powered by  <a href="https://github.com/falm">falm</a> .</p>
  </div>

</div>
</body>
</html>